./: lib{glbinding}

# Library Dependencies
include ../external/
intf_libs = ../external/lib{KHRplatform}

lib{glbinding}: $intf_libs

# Source File Dependencies
lib{glbinding}: \
  hxx{glbinding-version glbinding_export glbinding_features glbinding_api} \
  include/glbinding/{hxx ixx}{**} source/{hxx ixx cxx}{**}

# Code Generation
hxx{glbinding-version}: in{version} $src_root/manifest
{
  summary = $project.summary
  revision = ''
  dist = true
  clean = ($src_root != $out_root)
}
hxx{glbinding_export}: in{glbinding_export}
hxx{glbinding_api}: in{glbinding_api}: include = ($cxx.id != 'msvc')
hxx{glbinding_api}: in{glbinding_msvc_api}: include = ($cxx.id == 'msvc')

# Build Options
include_dirs = "-I$src_base/include" "-I$out_root" "-I$src_root"
cxx.poptions += $default.export.poptions $default.poptions $include_dirs
cxx.coptions += $default.export.coptions $default.coptions

obja{*}: cxx.poptions += -DGLBINDING_STATIC_DEFINE
objs{*}: cxx.poptions += -DGLBINDING_EXPORTS

# Export Options
lib{glbinding}:
{
  cxx.export.poptions = $default.export.poptions $include_dirs
  cxx.export.coptions = $default.export.coptions
  cxx.export.libs = $default.export.libs $intf_libs
}

liba{glbinding}: cxx.export.poptions += -DGLBINDING_STATIC_DEFINE
# libs{glbinding}: cxx.export.poptions +=

# Installation of Header Files
hxx{*}: install = include/glbinding/
source/{hxx ixx}{*}: install = false
include/{hxx ixx}{*}:
{
  install = include/
  install.subdirs = true
}
