./: lib{glbinding-aux}

# Sources
lib{glbinding-aux}: \
  hxx{glbinding-aux_export glbinding-aux_features} \
  include/glbinding-aux/{hxx ixx}{**} source/{hxx ixx cxx}{**}

hxx{glbinding-aux_api}: in{glbinding-aux_api}: include = ($cxx.id != 'msvc')
hxx{glbinding-aux_api}: in{glbinding-aux_msvc_api}: include = ($cxx.id == 'msvc')


# Configuration
include_dirs = "-I$src_base/include" "-I$out_root" "-I$src_root"
cxx.poptions =+ $include_dirs

import glbinding = glbinding%lib{glbinding}
lib{glbinding-aux}: $glbinding

lib{glbinding-aux}:
{
  cxx.export.poptions = $include_dirs
  cxx.export.libs = $glbinding
}

obja{*}: cxx.poptions += -DGLBINDING_AUX_STATIC_BUILD -DGLBINDING_AUX_STATIC_DEFINE
objs{*}: cxx.poptions += -DGLBINDING_AUX_SHARED_BUILD -DGLBINDING_AUX_EXPORTS

liba{glbinding-aux}: \
  cxx.export.poptions += -DGLBINDING_AUX_STATIC -DGLBINDING_AUX_STATIC_DEFINE
libs{glbinding-aux}: cxx.export.poptions += -DGLBINDING_AUX_SHARED

if (($cxx.target.class == 'linux') || ($cxx.target.class == 'macos'))
{
  # cxx.coptions += -fvisibility=hidden
  cxx.libs += -pthread
  lib{glbinding}: cxx.export.libs += -pthread
}

if ($cxx.target.class == 'windows')
{
  if ($cxx.id == 'msvc')
  {
    cxx.poptions += /D_SCL_SECURE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS
    cxx.coptions += /MP /W4 /wd4251 /wd4592 /wd4127 /Zm200 \
                    /Gw /GS- /GL /GF
  }
}

if ($cxx.id != 'msvc')
{
  lib{glbinding}: cxx.export.libs += -ldl
  cxx.libs += -ldl
}

# Installation
hxx{*}: install = include/glbinding-aux/
include/{hxx ixx}{*}:
{
  install = include/
  install.subdirs = true
}
source/{hxx ixx}{*}: install = false
