import libs = glbinding%lib{glbinding}
import libs += glbinding%lib{glbinding-aux}

import libs += glfw%lib{glfw}

import libs += gtest%lib{gtest}
import libs += gmock%lib{gmock}

exe{glbinding-test}: cxx{* -Multi* -Regression_test_1*} $libs
exe{glbinding-test}: cxx{Regression_test_1*}: include = $config.glbinding_tests.use_glfw_window

cxx.poptions += -DBUILD_GPU_TESTS
