import libs = glbinding%lib{glbinding}
import libs += glbinding%lib{glbinding-aux}

import libs += glfw%lib{glfw}

import libs += gtest%lib{gtest}
import libs += gmock%lib{gmock}

exe{glbinding-test}: cxx{* -Multi*} $libs

cxx.poptions += -DBUILD_GPU_TESTS
