import libs = glbinding%lib{glbinding}
import libs += glbinding-aux%lib{glbinding-aux}

import libs += glfw3%lib{glfw3}
cxx.poptions += -DGLFW_INCLUDE_NONE

./: {*/ -build/ -data/}

./: manifest legal{LICENSE} doc{README.md UPSTREAM.README.md AUTHORS}
doc{UPSTREAM.README.md}@./: install = doc/README.md
doc{README.md}@./: install = doc/PACKAGE.README.md
