./: lib{glbinding-aux}

# Library Dependencies
#
intf_libs = $default.intf_libs
impl_libs = $default.impl_libs
import intf_libs += lib{glbinding}
intf_libs = $cxx.deduplicate_export_libs($intf_libs)

# Source Dependencies
#
lib{glbinding-aux}: \
  hxx{glbinding-aux_features glbinding-aux_api} \
  include/glbinding-aux/{hxx ixx}{**} source/{hxx ixx cxx}{**}

# Add libraries at the end. Order is important.
# Otherwise, linking might fail due to 'undefined reference' errors.
#
lib{glbinding-aux}: $intf_libs $impl_libs

# Build Options
#
include_dirs = "-I$src_base/include" "-I$out_root" "-I$src_root"
cxx.poptions += $include_dirs
#
{hbmia obja}{*}: cxx.poptions += -DGLBINDING_AUX_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DGLBINDING_AUX_SHARED_BUILD

# Export Options
#
lib{glbinding-aux}:
{
  cxx.export.poptions = $default.export.poptions $include_dirs
  cxx.export.libs = $default.export.libs $intf_libs
}
#
liba{glbinding-aux}: cxx.export.poptions += -DGLBINDING_AUX_STATIC
libs{glbinding-aux}: cxx.export.poptions += -DGLBINDING_AUX_SHARED

# Library Version
#
lib{glbinding-aux}: bin.lib.version = "-$version.major.$version.minor"

# Installation of Header Files
#
hxx{*}: install = include/glbinding-aux/
source/{hxx ixx}{*}: install = false
include/{hxx ixx}{*}:
{
  install = include/
  install.subdirs = true
}
